#### User configurable options #####

########################################################################### 

MPI_HOME   		= /home/xcat_drbd_backup/xCATdrbd/opt_ohpc_pub/oneapi_basekit/mpi/2021.3.0
LIB_LIST   		= -qopenmp #-traceback
MPI_LIB    		= -L${MPI_HOME}/lib
MPI_INC    		= -I${MPI_HOME}/include
FLIBS      		= ${MPI_LIB} ${LIB_LIST} ${MPI_INC}
CPPC       		= ${MPI_HOME}/bin/mpiicpc
CPPLINKER  		= ${MPI_HOME}/bin/mpiicpc
#FFLAGS     		= -g -O3 -std=c++11
FFLAGS                  = -g -O3 -std=c++17 -fsycl -lsycl -fPIC
NVFLAGS                 = -g -lineinfo #-ccbin=/opt/ohpc/pub/compiler/gcc/5.4.0/bin/g++ -lmpi ${MPI_LIB} ${MPI_INC} -Xcompiler -fopenmp
#NVFLAGS    		= -g -lineinfo -ccbin=/opt/ohpc/pub/compiler/gcc/5.4.0/bin/g++ -lmpi ${MPI_LIB} ${MPI_INC} -Xcompiler -fopenmp
CPPFLAGS="-I/home/om/HPC/oneAPI/CDAC/dpct/SeisAcoMod2D/src/src_gpu/out-dpct"


#PGI_MPI_HOME 	= /opt/ohpc/pub/syssoftware/pgi/linux86-64-llvm/19.4/mpi/openmpi-3.1.3
#PGI_LIB_LIST 	= -acc -ta=tesla -Minfo=all -fast
#PGI_MPI_LIB  	= -L${PGI_MPI_HOME}/lib
#PGI_MPI_INC  	= -I${PGI_MPI_HOME}/include
#PGI_FLIBS 		= ${PGI_MPI_LIB} ${PGI_LIB_LIST} ${PGI_MPI_INC}

#PGI_CPPC       	= ${PGI_MPI_HOME}/bin/mpic++
#PGI_CPPLINKER  	= ${PGI_MPI_HOME}/bin/mpic++
#PGI_FFLAGS     	= -std=c++11


#############################################################################

